### ISSUE TITLE
Quantity not displayed

### ISSUE THREAD

**Issue by MastaGooz** [xaukael/griddy#1]
Hi !

Nice module, I love it !

I found some bugs and tried to fix it, but I'm js noob so maybe it's dumb as hell !

-The quantity is not displayed on objets in the grid.
I'm using Custom System Builder, and the quantity path is : system.props.quantity.
I put "props.quantity" in the module settings but nothing is showing up.
I corrected it by doing this : 

     // Reaffecting items
      items = character.items.filter(i => itemTypes.includes(i.type) && i.flags.griddy?.position?.e != true);
      if (container) {
          items = items.filter(i => i.flags.griddy.position.n && i.flags.griddy.position.n == container);
      } else {
          items = items.filter(i => !i.flags.griddy?.position.n);
      }

      // Add items to grid with quantity
    let itemElements = items.reduce((a, i) => a += 
    `<div id="${i.id}" name="${i.name}" class="item" draggable="true" data-uuid="${i.uuid}" data-stack-limit="${i.flags.griddy?.position?.s||0}"
        data-size="${i.flags.griddy?.position?.w*i.flags.griddy?.position?.h}" data-last-modified="${i._stats.createdTime}"
        data-tooltip="${i.name}${i.system[systemQuanityProp]>1?` (${i.system[systemQuanityProp]})`:''}" 
        style=" left: ${i.flags.griddy?.position?.x*gridSize}px; top: ${i.flags.griddy?.position?.y*gridSize}px; width:${i.flags.griddy?.position?.w*gridSize}px; height:${i.flags.griddy?.position?.h*gridSize}px; cursor:pointer">
        <img src="${i.img}" style="transform: translate(-50%, -50%); " >
        <span class="item-quantity" style="font-size:${gridSize / 4.5}px; position: absolute; top: 2px; left: 2px; color: white; background: rgba(0, 0, 0, 0.5); padding:1px 3px; display: ${i.system.props.quantity >= 1 ? 'inline' : 'none'}">${i.system.props.quantity}</span>
    </div>`, ``);
    html.find(`div.${id}`).html(itemElements);

-The resizing inventory et resizing item options are displayed even if "only GM" is set in the settings, i fixed it with : 

    if (resizing) {
    let gridConfig = $(`<a class="griddy-config" data-tooltip="Grid Config"><i class="fa-solid fa-cog"></i></a>`)
    gridConfig.click( function(e){
      let actor = app.object
      let configDialog = new Dialog({title:`${actor.name} Grid Config`,content:'', buttons:{},
        render: async (html)=>{
          let p = actor.flags.griddy?.config
          if (!p) {
            await actor.setFlag('griddy', 'config', {rows: 6, cols: 10})
            p = actor.flags.griddy?.config
          }
          let table = `<style>div.position-form span {line-height: var(--form-field-height);}</style>
          <div class="position-form" style="display:grid; grid-template-columns: repeat(4, 1fr); column-gap: 1em; row-gap: .2em">`
          table += `
          <span>columns:</span><input  name="cols" type="number" value="${p.cols||1}" autofocus></input>
          <span>rows:</span><input  name="rows" type="number" value="${p.rows||1}"></input>`
          table+=`</div><button style="margin-top: .2em">Save</button>`
          html[0].innerHTML = table
          html.find('button').click(async function(){
            let config = [...html.find('input')].reduce((a, e)=>{
              return Object.assign(a, {[e.getAttribute('name')]: Number(e.value)})
            },{})
            await actor.setFlag('griddy', 'config', config)
            ui.notifications.info(`Updated ${actor.name} Griddy flags: ${JSON.stringify(config)}`)
            d.close()
            configDialog.close()
          }).on('keydown', function(e){
            e.stopPropagation()
            if (e.key=='Enter') this.click()
          })
          html.find('input').focusin(function(){this.select()}).on('keydown', function(e){
            e.stopPropagation()
            if (e.key=='Enter') html.find('button').click()
          })
          
        },
        close: ()=>{  return;}
        },{top: e.clientY , left: e.clientX, width: 250, height: 'auto'}).render(true)
      
    });
    header.after(gridConfig).after(autoSort)
    }
 
and : 

    if (game.settings.get('griddy', 'resizing') && resizing)
    buttons.unshift({

**Comment by xaukael** [comment]
Am I correct that the issue with quantity not showing was that you wanted the quantity showing even if there is only one? I thought this would have been apparent by the code and the screenshot in the module description. This was intentional. I left it as something that could easily be changed in the renderGriddy hook or even just custom css.

Resizing the grid is something I added last and I had not decided how/if I wanted to restrict access to that. That is why the hint on the setting said it was for item resizing. I split the resizing setting to Item Resizing and Grid Resizing for the grid in version 1.0.4.

The resizing check was my goof. I forgot I made choices rather than true false. Not sure why you did what you did bit I change the item resizing button check to: 
`if (game.settings.get('griddy', 'itemResizing')=="GM"?game.user.isGM:false)`

**Comment by xaukael** [comment]
I was thinking about adding another filter to filter out items of 0 quantity, but this is effectively the same as excluding them or just deleting the item. In either case, you would have to go back to the system sheets or directory to get them back.
I am add a setting to allow showing of item quantities even at 1

**Comment by MastaGooz** [comment]
Thanks for your answer, 

No I was not talking about "1" quantity. 

![image](https://github.com/xaukael/griddy/assets/149971487/3f56d193-9f5d-44af-8e52-6dd0dcc33b0e)

This is what I get with the last version.
Using Custom System Builder with the path : system.props.quantity.
So I put "props.quantity" in the settings but it don't work (it was working with the patch I did, but I'm no dev and I just do random shit until it work lmao).

**Comment by xaukael** [comment]
I was unable to tell what you did in the patch except change the `>1` to `>=1` can you indicate what it is that you did to fix it.?

**Comment by xaukael** [comment]
never mind, it was because it was not a direct property of system. I switched to a function that should work no matter how far it is nested in v 1.0.11. Can you confirm?

**Comment by MastaGooz** [comment]
Yes, it now works perfectly, thank !
