### ISSUE TITLE
Other way to include items in the grid?

### ISSUE THREAD

**Issue by MastaGooz** [xaukael/griddy#10]
Hi ! 

I'm using Custom System Builder, and getting the items "type" to select wich items should go on the grid is not working because there is only 2 types : templates (_equippableItemTemplate : used to create items "types" in the system) and the actual items (equippableItem : you have to select a template for the item when creating it). 

So I have no way to tell the module what kinf of items should go to the grid or not (since I can only put "equippableItem", so every item in the game).

Could it be possible to set an alternative way to set this? Like maybe set an item property to tell the module if the item should go or not in the grid? Like for the system quantity. So I can put true/false to that property?

I hope i'm being understandable. 

Take care

**Comment by xaukael** [comment]
I sort of anticipated that DIY systems would have such a problem where every item has the same type. The way I see getting around this would be to have every item like you said, and then set the exclude flag for ones you do not want included. `item.setFlag('griddy', 'position.e', true)` you could also do mass applications of this with a macro `Item.updateDocuments([{_id: "item id", "flags.griddy.position.e": true}])`. I also considered adding a hook to the beginning of the render that would allow custom logic for filtering items with a world script, but I think setting the exclude flag is easier to understand.

**Comment by MastaGooz** [comment]
Ok nice, thanks man !

**Comment by xaukael** [comment]
I added a hook to use in world scripts. Items in this context is a Set that needs to be modified. This can look scary to do because it can almost look like you will be deleting the item from the actor rather than just from the set.

```js
Hooks.on('filterGriddyItems', (items)=>{
  return true;
  items.forEach((i) => {
    if (i.type!="weapon") 
      items.delete(i);
  });
})
```

**Comment by MastaGooz** [comment]
Ok, very nice ! Thanks

**Comment by MastaGooz** [comment]
I tested the hook on the world script.

There is a little problem tho : even if the items don't appear in the grid, it seems that they are still counted as taking a slot. I can see that when I use the macro that you gave me.

**Comment by xaukael** [comment]
that depends on what you mean by taking a slot. Technically, the items you delete from the set still have the flags, but they are not considered there by griddy, so it doesn't matter.

**Comment by xaukael** [comment]
as for the macro, update the filter to remove the items that you remove from the set

**Comment by MastaGooz** [comment]
My bad, I forgot to update the macro...
