### ISSUE TITLE
Containers vanish -- resolved

### ISSUE THREAD

**Issue by FallhammerLord** [xaukael/griddy#14]
Container items no longer appear in the grid. Tested with all modules off w/ just Griddy. Backpacks are not set to "exclude".

Foundry v.11 Stable
D&D 5e 3.0.4

![image](https://github.com/xaukael/griddy/assets/162035784/bdc32723-2307-4837-8f88-d26f53a21d6a)

**Comment by xaukael** [comment]
What are the item types in the griddy settings?

**Comment by FallhammerLord** [comment]
> What are the item types in the griddy settings?

Ah, I'm not as thorough as I thought! thank you.
