### ISSUE TITLE
Request: 1/4 Items

### ISSUE THREAD

**Issue by MsVella** [xaukael/griddy#15]
this isn't strictly speaking an issue (hence why i've marked it as such), but i'd love to see 1/4 tile items if they are not already implemented, i'll also be testing this mod if it works for my game and reporting back any issues I run into!

**Comment by xaukael** [comment]
Quarter tiles would break all the logic that makes the module functions which depends on whole numbers. I suggest making the smallest considered item the unit of measure. 

Another option that might work is having a small items container. There would be no hard coded restrictions for the "size" of items in there, but there are plenty of honor rules in tabletop games and the use of the module already.

**Comment by MsVella** [comment]
Understandable! I'm also working on a much larger list of suggestions as I use the module, that I may put here at some point if you're interested in humoring me. I've noticed that it's really really robust, and I haven't really ran into any major problems.
