### ISSUE TITLE
[Request] Picture scale option and picture stretch option

### ISSUE THREAD

**Issue by MsVella** [xaukael/griddy#18]
I'd like to see an option for both allowing item pictures to be stretched across the whole item in a griddy inventory, and an option in the options for universal picture "scale", in case of situation like below:
![example](https://github.com/user-attachments/assets/5666157a-34de-4779-86e1-0ac22457aff8)

Although I guess i'd give bonus points if all of this could be done in the options, or on an individual item basis

**Comment by xaukael** [comment]
I fought with the CSS very early in development of this to get the images to keep the original image aspect ratio and fit within the item div. Given that I assume you want to be able to set these per item, this would be very difficult to implement without significant rewrite. If you want the effect in the image you provided, you can modify the image file to have more space around the image.

**Comment by MsVella** [comment]
understandable
