### ISSUE TITLE
Incompability with A5e (and possibly more) systems

### ISSUE THREAD

**Issue by joeundsoo** [xaukael/griddy#2]
Hello there, great idea for a module!
Sadly, I've run into a compability problem with the [system I am using](https://foundryvtt.com/packages/a5e). I'm using the most recent Foundry Build (315) and A5e Version (0.16.15).
Neither clicking on Inventory Grid or Griddy in the character sheet opens the Griddy Menu and an error message is sent to the console.
![image](https://github.com/xaukael/griddy/assets/71326670/6922524f-e5fa-4a50-afa7-86ab87f0d898)

The system dev looked into it: 
![image](https://github.com/xaukael/griddy/assets/71326670/ff24fcec-490a-44e9-a8ff-13bb6ddfcc25)
After modifying the module, the Griddy Menu opens. Items are displayed correctly inside the grid and so on.  But when it comes to changing the properties of an item (making it take more squares, turning it into a container..), the button for that setting still isn't portrayed in the item sheet. 

The dev mentioned, that the way of getting the actor could be more robust, because of the coming appv2 in Foundry v12.
![image](https://github.com/xaukael/griddy/assets/71326670/892d9762-c8a4-4ee6-a4cb-1973787c8b95)
The A5e system for example doesn't use handlebars, but svelte.

I don't know how to code myself, so I don't know how difficult it would be to provide a better compability...

If there's anything else needed for a possible fix, I'm glad to help!

**Comment by xaukael** [comment]
Remove quotes on the item types settings.

Fixed the sheet header buttons using app.object/app.document in 1.0.8. Thank you so much for the heads-up.

**Comment by xaukael** [comment]
That is odd. Any errors?

**Comment by xaukael** [comment]
Nevermind, I missed some app.object references. should be fixed in 1.0.9

**Comment by joeundsoo** [comment]
Yes, that's it. Awesome, it's working. Thank you so much for the quick fixes!

**Comment by xaukael** [comment]
going on holiday for 5 days starting tomorrow. Trying to not have to think about it too much while gone
