### ISSUE TITLE
[DnD 5e] Can't configure grid

### ISSUE THREAD

**Issue by megahead11** [xaukael/griddy#3]
When attempting to configure the grid using the gear icon at the top of the griddy window, I get this error and nothing opens up.
![image](https://github.com/xaukael/griddy/assets/21242682/13aec227-294d-4170-9b03-970b651a7214)

This is on DnD 2.4.1, Foundry v11.315.
The only other module I have active at the moment is Module Management+ (for mass disabling modules)

**Comment by xaukael** [comment]
Thank you for bringing this to my attention. This was due to over-correction of an earlier issue. fixed in 1.0.10
