### ISSUE TITLE
Simply world-building

### ISSUE THREAD

**Issue by NeruleFR** [xaukael/griddy#4]
Hello Xaukael, I have a request for your foundry module! I would like to know if you could make it work with simply world-building? Because currently and obviously it only works with D&D systems.

![Capture d'écran 2023-12-29 025918](https://github.com/xaukael/griddy/assets/155125256/29664102-c9c8-4d67-8b28-a03cb18ff76d)

**Comment by xaukael** [comment]
It works. Some configuration required. 
![image](https://github.com/xaukael/griddy/assets/37848032/22145d44-d5c9-45a2-a807-f1e9f499f348)

**Comment by NeruleFR** [comment]
Ty! And no more configuration required
