### ISSUE TITLE
Skills showing in Grid as undefined

### ISSUE THREAD

**Issue by ubercatz** [xaukael/griddy#5]
im aware you have to add the item types so that griddy will be able to tell what it is that goes into bags, i added "base, weapon, equipment, consumable, loot, class, spell, feat, buff, attack, race, container" to the item types field for Pathfinder 1e, but my class features still show up in the bag as undefined as in the picture.
![image](https://github.com/xaukael/griddy/assets/155195884/5d430050-7a3f-4051-a436-314cbbcd6b63)
Im unsure if this was an issue with my input or w/ the pathfinder syste tho i assume i made some error

**Comment by xaukael** [comment]
What is displaying as undefined is the quantity, which I assume is not part of the item properties of class features, spells, etc. I will work on having the quantity not show if quantity is undefined.

Why are you including class features?

**Comment by ubercatz** [comment]
ah i see now, i put all the available option in instead of just items lol! thanks!
